services:

  islob-bot:
    build: .
    container_name: islob-bot
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - islob-network
    command: >
      sh -c "
        python main.py
      "

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    command: uvicorn web_app.main:app --host 0.0.0.0 --port 8080 --reload
    networks:
      - islob-network

networks:
  islob-network:
    driver: bridge
